CREATE TABLE [dbo].[OnlineStats](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[InsertTime] [datetime] NOT NULL,
	[Counter] [int] NOT NULL,
 CONSTRAINT [PK_OnlineStats] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


